<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>isaac_ros_e2e_traj_control</name>
  <version>0.0.1</version>
  <description>NITROS Encoder for nav_msgs::msg::Odometry history</description>

  <maintainer email="user@example.com">ROS User</maintainer>
  <license>Apache-2.0</license>
  <url type="website">https://developer.nvidia.com/isaac-ros-gems/</url>
  <author>ROS User</author>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>rclcpp_components</depend>
  <depend>std_msgs</depend> <depend>nav_msgs</depend> <depend>isaac_ros_managed_nitros</depend>
  <depend>isaac_ros_tensor_list_interfaces</depend>
  <depend>isaac_ros_nitros_tensor_list_type</depend>

  <build_depend>isaac_ros_common</build_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>