/**:
  ros__parameters:
    input_topics:
      race_mode: "/ackermann_cmd_race"
      540_mode: "/ackermann_cmd_540"

    section_to_mode:
      0: "race_mode"
      1: "540_mode"
      2: "540_mode"
      3: "540_mode"
      4: "race_mode"

    output_topic: "/ackermann_cmd"
    section_topic: "current_section"
