/**:
  ros__parameters:
    mode_topic: "/current_mode"
    output_topic: "/ackermann_cmd"
    # 起動時のデフォルトモード (0: race_mode, 1: 540_mode)
    default_mode: 0 
    # 'input_topics' をモードID (配列インデックス) 順のリストにする
    input_topics:
      - "/ackermann_cmd_race"  # Index 0 (Mode 0)
      - "/ackermann_cmd_540"  # Index 1 (Mode 1)