# config/analyze.yaml

# --- パス設定 ---
data_path: "./datasets/test"  # 分析したいデータセット 
ckpt_path: null # 読み込むモデル

load_weights:
  # path_generation で学習した重み
  trajformer_path: null
  # path_follow で学習した重み
  controlnet_path: null

# --- モデルのどの部分を読み込むか ---
# trajformer_only or all
load_part: all # all, trajformer_only, control_only

# --- デバイス ---
device: cuda 

# --- データセット (train.yaml と合わせる) ---
dataset:
  image_height: 120
  image_width: 160
  past_len: 10       
  future_len: 30      

# --- 学習 (Dataloaderの num_workers のために必要) ---
training:
  num_workers: 8

# --- モデル (train.yaml と合わせる) ---
model:
  # --- 共通 ---
  odom_features: 8              

  # --- TrajFormer パラメータ ---
  image_embedding_dim: 128
  motion_embedding_dim: 64
  transformer_d_model: 192      
  transformer_nhead: 6
  transformer_num_layers: 2

  # --- ControlFormer パラメータ ---
  control_motion_embedding_dim: 64
  control_d_model: 64
  control_nhead: 4
  control_num_layers: 2

analysis:
  select_sequences: [0] 
  
  # BEVの解像度 (ピクセル/メートル)
  pixels_per_meter: 50
  
  # コマンドの最大値 (データセットや正規化に合わせる)
  max_steer_rad: 0.6 
  max_speed_ms: 2.0  
  
  # コマンドパネルに描画する未来ステップ数
  cmd_steps_to_draw: 5

hydra:
  run:
    dir: ./outputs/analyze/${now:%Y-%m-%d}/${now:%H-%M-%S}