# --- データ関連の設定 ---
data_path: "./datasets/"  # TrajectoryDataset の出力ディレクトリ
resume_ckpt_path: null

load_weights:
  # path_generation で学習した重み
  trajformer_path: null
  # path_follow で学習した重み
  controlnet_path: null

# --- データセットと変換の設定 ---
dataset:
  image_height: 120
  image_width: 160
  past_len: 10          # 過去オドメトリの履歴長
  future_len: 30       # 未来軌跡の長さ
# --- 学習パラメータ ---
training:
  # --- 【重要】モード切り替え ---
  # 'all' : E2E学習
  # 'path_generation' : 軌道予測 (TrajFormer) のみ学習
  # 'path_follow' : 制御 (ControlFormer) のみ学習
  mode: all 

  batch_size: 64
  epochs: 100
  learning_rate: 0.0003
  num_workers: 8

  # 'path_follow' モード時に正解パス(Ground Truth)を使用する確率
  # 1.0 = 常に正解パス (元の動作)
  # 0.8 = 80%は正解パス, 20%は予測パス
  # 0.0 = 常に予測パス
  scheduled_sampling_prob: 0.6

  # --- 損失の重み (各モードで必要なものだけが使われます) ---
  loss_weights:
    traj: 1.0     
    cmd: 0.5      
    smooth: 0.1

# --- モデルのパラメータ ---
model:
  odom_dim: 8
  image_embedding_dim: 128
  motion_embedding_dim: 64
  d_model: 192  
  transformer_nhead: 6
  transformer_num_layers: 2
  control_d_model: 64
  control_nhead: 4
  control_num_layers: 2


# --- ログ・チェックポイント ---
log_dir: ./logs/train/${now:%Y-%m-%d}/${now:%H-%M-%S}  
ckpt_dir: ./ckpts/train/${now:%Y-%m-%d}/${now:%H-%M-%S}  

# --- Hydra 実行ディレクトリ ---
hydra:
  run:
    dir: ./outputs/train/${now:%Y-%m-%d}/${now:%H-%M-%S}
