# --- データ関連の設定 ---
data_path: "./dataset/extracted/"  # データ抽出スクリプトの出力ディレクトリ

# --- データセットと変換の設定 ---
dataset:
  sequence_length: 1
  image_height: 120
  image_width: 160
  train_val_split_ratio: 0.8 # 学習データと検証データの分割比率

# --- 学習パラメータ ---
training:
  epochs: 50
  batch_size: 64
  learning_rate: 0.0001
  num_workers: 4

# --- モデルのパラメータ ---
model:
  num_outputs: 2

log_dir: ./logs/train/${now:%Y-%m-%d}/${now:%H-%M-%S}  
ckpt_dir: ./ckpts/train/${now:%Y-%m-%d}/${now:%H-%M-%S}  

hydra:
  run:
    dir: ./outputs/train/${now:%Y-%m-%d}/${now:%H-%M-%S}